// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Mail.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.MailModule;

final class _AMD_MailAmd_sendMail extends IceInternal.IncomingAsync implements AMD_MailAmd_sendMail
{
    public _AMD_MailAmd_sendMail(IceInternal.Incoming in)
    {
        super(in);
    }

    public void ice_response(boolean __ret)
    {
        if(__validateResponse(true))
        {
            try
            {
                IceInternal.BasicStream __os = this.__startWriteParams(Ice.FormatType.DefaultFormat);
                __os.writeBool(__ret);
                this.__endWriteParams(true);
            }
            catch(Ice.LocalException __ex)
            {
                __exception(__ex);
                return;
            }
            __response();
        }
    }
}
