// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Mail.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.MailModule;

/**
 * Provides type-specific helper functions.
 **/
public final class MailAmdPrxHelper extends Ice.ObjectPrxHelperBase implements MailAmdPrx
{
    private static final String __sendMail_name = "sendMail";

    public boolean sendMail(String phone)
    {
        return sendMail(phone, null, false);
    }

    public boolean sendMail(String phone, java.util.Map<String, String> __ctx)
    {
        return sendMail(phone, __ctx, true);
    }

    private boolean sendMail(String phone, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__sendMail_name);
        return end_sendMail(begin_sendMail(phone, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sendMail(String phone)
    {
        return begin_sendMail(phone, null, false, false, null);
    }

    public Ice.AsyncResult begin_sendMail(String phone, java.util.Map<String, String> __ctx)
    {
        return begin_sendMail(phone, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sendMail(String phone, Ice.Callback __cb)
    {
        return begin_sendMail(phone, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendMail(String phone, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sendMail(phone, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendMail(String phone, Callback_MailAmd_sendMail __cb)
    {
        return begin_sendMail(phone, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sendMail(String phone, java.util.Map<String, String> __ctx, Callback_MailAmd_sendMail __cb)
    {
        return begin_sendMail(phone, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendMail(phone, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMail(phone, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sendMail(phone, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMail(phone, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sendMail(String phone, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sendMail(phone, __ctx, __explicitCtx, __synchronous, 
                              new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                  {
                                      public final void __completed(Ice.AsyncResult __result)
                                      {
                                          MailAmdPrxHelper.__sendMail_completed(this, __result);
                                      }
                                  });
    }

    private Ice.AsyncResult begin_sendMail(String phone, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__sendMail_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sendMail_name, __cb);
        try
        {
            __result.prepare(__sendMail_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(phone);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_sendMail(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __sendMail_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __sendMail_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        MailAmdPrx __proxy = (MailAmdPrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_sendMail(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MailAmdPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), MailAmdPrx.class, MailAmdPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MailAmdPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), MailAmdPrx.class, MailAmdPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MailAmdPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), MailAmdPrx.class, MailAmdPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MailAmdPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), MailAmdPrx.class, MailAmdPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static MailAmdPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, MailAmdPrx.class, MailAmdPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static MailAmdPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, MailAmdPrx.class, MailAmdPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::MailModule::MailAmd"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, MailAmdPrx v)
    {
        __os.writeProxy(v);
    }

    public static MailAmdPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MailAmdPrxHelper result = new MailAmdPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
