// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.MessageModule;

public interface Sms extends Ice.Object,
                             _SmsOperations, _SmsOperationsNC
{
    public static final String ice_staticId = "::MessageModule::Sms";

    public static final long serialVersionUID = 486775105L;
}
