// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.MessageModule;

public interface SmsPrx extends Ice.ObjectPrx
{
    public boolean sendSms(String phone);

    public boolean sendSms(String phone, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSms(String phone);

    public Ice.AsyncResult begin_sendSms(String phone, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSms(String phone, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSms(String phone, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSms(String phone, Callback_Sms_sendSms __cb);

    public Ice.AsyncResult begin_sendSms(String phone, java.util.Map<String, String> __ctx, Callback_Sms_sendSms __cb);

    public Ice.AsyncResult begin_sendSms(String phone,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendSms(String phone,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendSms(String phone,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendSms(String phone,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_sendSms(Ice.AsyncResult __result);
}
