// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Monitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.feng.MMonitor;

public interface Monitor extends Ice.Object,
                                 _MonitorOperations, _MonitorOperationsNC
{
    public static final String ice_staticId = "::MMonitor::Monitor";

    public static final long serialVersionUID = -734647632L;
}
