// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.model.orderModule;

public interface _OrderServiceOperations
{
    void addOrder_async(AMD_OrderService_addOrder __cb, Order order, Ice.Current __current);

    boolean payOrder(long orderId, Ice.Current __current);

    Order getOrder(long orderId, Ice.Current __current);

    boolean endOrder(long orderId, Ice.Current __current);

    void shutdown(Ice.Current __current);
}
