// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.model.orderModule;

public interface OrderServicePrx extends Ice.ObjectPrx
{
    public boolean addOrder(Order order);

    public boolean addOrder(Order order, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addOrder(Order order);

    public Ice.AsyncResult begin_addOrder(Order order, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addOrder(Order order, Ice.Callback __cb);

    public Ice.AsyncResult begin_addOrder(Order order, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addOrder(Order order, Callback_OrderService_addOrder __cb);

    public Ice.AsyncResult begin_addOrder(Order order, java.util.Map<String, String> __ctx, Callback_OrderService_addOrder __cb);

    public Ice.AsyncResult begin_addOrder(Order order, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addOrder(Order order, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_addOrder(Order order, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_addOrder(Order order, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_addOrder(Ice.AsyncResult __result);

    public boolean payOrder(long orderId);

    public boolean payOrder(long orderId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_payOrder(long orderId);

    public Ice.AsyncResult begin_payOrder(long orderId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_payOrder(long orderId, Ice.Callback __cb);

    public Ice.AsyncResult begin_payOrder(long orderId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_payOrder(long orderId, Callback_OrderService_payOrder __cb);

    public Ice.AsyncResult begin_payOrder(long orderId, java.util.Map<String, String> __ctx, Callback_OrderService_payOrder __cb);

    public Ice.AsyncResult begin_payOrder(long orderId, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_payOrder(long orderId, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_payOrder(long orderId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_payOrder(long orderId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_payOrder(Ice.AsyncResult __result);

    public Order getOrder(long orderId);

    public Order getOrder(long orderId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getOrder(long orderId);

    public Ice.AsyncResult begin_getOrder(long orderId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getOrder(long orderId, Ice.Callback __cb);

    public Ice.AsyncResult begin_getOrder(long orderId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getOrder(long orderId, Callback_OrderService_getOrder __cb);

    public Ice.AsyncResult begin_getOrder(long orderId, java.util.Map<String, String> __ctx, Callback_OrderService_getOrder __cb);

    public Ice.AsyncResult begin_getOrder(long orderId, 
                                          IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getOrder(long orderId, 
                                          IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getOrder(long orderId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getOrder(long orderId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<Order> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Order end_getOrder(Ice.AsyncResult __result);

    public boolean endOrder(long orderId);

    public boolean endOrder(long orderId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_endOrder(long orderId);

    public Ice.AsyncResult begin_endOrder(long orderId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_endOrder(long orderId, Ice.Callback __cb);

    public Ice.AsyncResult begin_endOrder(long orderId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_endOrder(long orderId, Callback_OrderService_endOrder __cb);

    public Ice.AsyncResult begin_endOrder(long orderId, java.util.Map<String, String> __ctx, Callback_OrderService_endOrder __cb);

    public Ice.AsyncResult begin_endOrder(long orderId, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_endOrder(long orderId, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_endOrder(long orderId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_endOrder(long orderId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_endOrder(Ice.AsyncResult __result);

    public void shutdown();

    public void shutdown(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shutdown();

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shutdown(Ice.Callback __cb);

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_shutdown(Callback_OrderService_shutdown __cb);

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx, Callback_OrderService_shutdown __cb);

    public Ice.AsyncResult begin_shutdown(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_shutdown(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_shutdown(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_shutdown(Ice.AsyncResult __result);
}
