// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.model.orderModule;

public interface OrderService extends Ice.Object,
                                      _OrderServiceOperations, _OrderServiceOperationsNC
{
    public static final String ice_staticId = "::orderModule::OrderService";

    public static final long serialVersionUID = 1875828762L;
}
