// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.model.orderModule;

public enum UserRole implements java.io.Serializable
{
    
    ADMIN(0),
    
    VIP(1),
    
    VISITOR(2);

    public int
    value()
    {
        return __value;
    }

    public static UserRole
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return ADMIN;
        case 1:
            return VIP;
        case 2:
            return VISITOR;
        }
        return null;
    }

    private
    UserRole(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 2);
    }

    public static void
    __write(IceInternal.BasicStream __os, UserRole __v)
    {
        if(__v == null)
        {
            __os.writeEnum(com.txmd.generate.model.orderModule.UserRole.ADMIN.value(), 2);
        }
        else
        {
            __os.writeEnum(__v.value(), 2);
        }
    }

    public static UserRole
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(2);
        return __validate(__v);
    }

    private static UserRole
    __validate(int __v)
    {
        final UserRole __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
