// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Mail.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.MailModule;

public interface MailAmdPrx extends Ice.ObjectPrx
{
    public boolean sendMail(String phone);

    public boolean sendMail(String phone, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMail(String phone);

    public Ice.AsyncResult begin_sendMail(String phone, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMail(String phone, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMail(String phone, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMail(String phone, Callback_MailAmd_sendMail __cb);

    public Ice.AsyncResult begin_sendMail(String phone, java.util.Map<String, String> __ctx, Callback_MailAmd_sendMail __cb);

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMail(String phone, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_sendMail(Ice.AsyncResult __result);
}
