// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Mail.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.MailModule;

public interface MailAmd extends Ice.Object,
                                 _MailAmdOperations, _MailAmdOperationsNC
{
    public static final String ice_staticId = "::MailModule::MailAmd";

    public static final long serialVersionUID = -1555669297L;
}
