// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `DemoIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.helloworld;

public interface Hello extends Ice.Object,
                               _HelloOperations, _HelloOperationsNC
{
    public static final String ice_staticId = "::helloworld::Hello";

    public static final long serialVersionUID = 1407818015L;
}
