// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `DemoIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.helloworld;

public interface _HelloOperations
{
    void sayHello(int delay, Ice.Current __current);

    String helloWorld(String name, Ice.Current __current);

    void shutdown(Ice.Current __current);
}
