// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.book;

public interface OnlineBookPrx extends Ice.ObjectPrx
{
    public Message bookTicket(Message msg);

    public Message bookTicket(Message msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bookTicket(Message msg);

    public Ice.AsyncResult begin_bookTicket(Message msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_bookTicket(Message msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_bookTicket(Message msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_bookTicket(Message msg, Callback_OnlineBook_bookTicket __cb);

    public Ice.AsyncResult begin_bookTicket(Message msg, java.util.Map<String, String> __ctx, Callback_OnlineBook_bookTicket __cb);

    public Ice.AsyncResult begin_bookTicket(Message msg,
                                            IceInternal.Functional_GenericCallback1<Message> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bookTicket(Message msg,
                                            IceInternal.Functional_GenericCallback1<Message> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_bookTicket(Message msg,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<Message> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_bookTicket(Message msg,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<Message> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Message end_bookTicket(Ice.AsyncResult __result);
}
