
zeroc:
  ice:
    config:
      iceCfgFilePath: config.server
      iceAppName: TxmdIceServer
      iceAdapterName: TxmdIceServerAdapter
      iceServantMap:
        hello: com.txmd.service.HelloImpl