// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.txmd.generate.book;

public abstract class Callback_OnlineBook_bookTicket
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<com.txmd.generate.book.Message>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        OnlineBookPrxHelper.__bookTicket_completed(this, __result);
    }
}
